name: Setup Node
description: Setup Node

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Set Up Pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - id: pnpm-cache-dir-path
      run: echo "::set-output name=dir::$(pnpm store path)"
      shell: bash

    - uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
