# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      prod-patch-update:
        dependency-type: "production"
        update-types: ["patch"]
      prod-minor-update:
        dependency-type: "production"
        update-types: ["minor"]
      prod-major-update:
        dependency-type: "production"
        update-types: ["major"]
      dev-patch-update:
        dependency-type: "development"
        update-types: ["patch"]
      dev-minor-update:
        dependency-type: "development"
        update-types: ["minor"]
      dev-major-update:
        dependency-type: "development"
        update-types: ["major"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docs-update:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/admin-frontend/"
    schedule:
      interval: "monthly"
    groups:
      prod-patch-update:
        dependency-type: "production"
        update-types: ["patch"]
      prod-minor-update:
        dependency-type: "production"
        update-types: ["minor"]
      prod-major-update:
        dependency-type: "production"
        update-types: ["major"]
      dev-patch-update:
        dependency-type: "development"
        update-types: ["patch"]
      dev-minor-update:
        dependency-type: "development"
        update-types: ["minor"]
      dev-major-update:
        dependency-type: "development"
        update-types: ["major"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions-update:
        patterns:
          - "*"
