name: Build Docs
description: Build Docs

runs:
  using: "composite"
  steps:
    - name: Setup Node Environment
      uses: ./.github/actions/setup-node

    - name: Build Frontend
      shell: bash
      run: |
        pnpm install
        pnpm docs:build
