coverage:
  status:
    project: off
    patch: off

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 5%
      - type: patch
        target: 60%
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: all-test
      carryforward: true
      statuses:
        - type: project
          target: auto
          threshold: 5%
        - type: patch
          target: 80%
