{
 "title": "NoneBot Status Overview",
 "description": "NoneBot Status Overview Dashboard provided by nonebot-plugin-prometheus \r\nsource: https://github.com/suyiiyii/nonebot-plugin-prometheus",
 "tags": [ "NoneBot" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values(nonebot_start_at,instance)"
    }
   },
   {
    "name": "user",
    "label": "筛选用户",
    "query": {
     "query": "label_values(nonebot_sent_messages_created,user_id)"
    }
   },
   {
    "name": "matcher",
    "label": "筛选Matcher",
    "query": {
     "query": "label_values(nonebot_matcher_duration_seconds_count,matcher_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Python 版本",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "python_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "运行时长",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - nonebot_start_at{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bot 在线数量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nonebot_bot_nums{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "收到消息",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nonebot_received_messages_total{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "发出消息",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nonebot_sent_messages_total{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Python GC 情况",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "rate(python_gc_objects_collected_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bot 在线情况",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "nonebot_bot_nums{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bot 离线次数",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "nonebot_bot_shutdown_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Matcher Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Matcher 调用",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "increase(nonebot_matcher_calling_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Matcher 响应时间（接受筛选）",
   "type": "heatmap",
   "description": "响应器运行时间",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by(le) (increase(nonebot_matcher_duration_seconds_bucket{instance=\"$instance\",matcher_name=~\"$matcher\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Message Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "bot 收到消息（接受筛选）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(nonebot_received_messages_total{instance=\"$instance\",user_id=~\"$user\"}[$__rate_interval])) by (adapter_name,bot_id,user_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "bot 发出消息（接受筛选）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(nonebot_sent_messages_total{instance=\"$instance\",user_id=~\"$user\"}[$__rate_interval])) by (adapter_name,bot_id,user_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "收到用户消息排行",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "nonebot_received_messages_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "发送用户消息排行",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "nonebot_sent_messages_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}