{
 "title": "Bison Status",
 "description": "Bison Status by nonebot-bison\nsource: https://github.com/MountainDash/nonebot-bison",
 "tags": [ "NoneBot" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "运行时长",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time() - bison_start_time", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "总请求数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bison_request_counter_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总请求失败数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bison_request_counter_total{success!=\"True\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总发送消息数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bison_sent_counter_total) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "当前请求速率",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(bison_request_counter_total[1m]) * 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "当前失败率",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(bison_request_counter_total{success!=\"True\"}[1m])) * 60 or vector(0)) /sum(rate(bison_request_counter_total[1m]) * 60) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "发送消息",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bison_sent_counter_total) by (platform_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "活跃调度对象",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (platform_name) (bison_request_counter_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "错误详情",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bison_request_counter_total{success=\"False\"}) by (platform_name,target)",
     "legendFormat": "{{platform_name}} - {{target}}"
    }
   ]
  },
  {
   "title": "平均请求耗时",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bison_request_histogram_sum / bison_request_histogram_count) by (platform_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "平均渲染耗时",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bison_render_histogram_sum / bison_render_histogram_count ) by (platform_name)",
     "legendFormat": "{{platform_name}}"
    }
   ]
  },
  {
   "title": "每分钟请求次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(bison_request_counter_total[1m])* 60)  by (platform_name)",
     "legendFormat": "{{platform_name}}"
    }
   ]
  },
  {
   "title": "Cookie 调度数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(bison_cookie_choose_counter_total[1m]) * 60) by (cookie_id)",
     "legendFormat": "{{site_name}} - {{cookie_id}}"
    }
   ]
  },
  {
   "title": "请求详情",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(bison_request_counter_total[1m]) * 60",
     "legendFormat": "{{platform_name}} - {{target}}"
    }
   ]
  },
  {
   "title": "Cookie 调度详情",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(bison_cookie_choose_counter_total[1m]) * 60",
     "legendFormat": "{{site_name}} - {{target}} - {{cookie_id}}"
    }
   ]
  },
  {
   "title": "平均请求耗时",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(bison_request_histogram_bucket[1m])*60) by (le)",
     "legendFormat": "{{platform_name}}"
    }
   ]
  },
  {
   "title": "发送消息详情",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "rate(bison_sent_counter_total[1m]) * 60",
     "legendFormat": "{{platform_name}}"
    }
   ]
  }
 ]
}