name: Setup Python
description: Setup Python

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.10"
  install-deps:
    description: Install dependencies
    required: false
    default: "false"
  install-playwright:
    description: Install Playwright
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
        enable-cache: true

    - name: Install dependencies
      if: ${{ inputs.install-deps == 'true' }}
      run: uv sync --frozen
      shell: bash

    - name: Install Playwright
      if: ${{ inputs.install-playwright == 'true' }}
      run: uv run playwright install
      shell: bash
