class CeobeResponseError(Exception): ...


class CeobeSnapshotException(Exception): ...


class CeobeSnapshotSkip(CeobeSnapshotException): ...


class CeobeSnapshotFailed(CeobeSnapshotException): ...
