"""empty message

Revision ID: 9eb14d3b7904
Revises: 5da28f6facb3
Create Date: 2023-01-15 19:09:28.371244

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9eb14d3b7904'
down_revision = '5da28f6facb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nonebot_bison_scheduletimeweight', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('nonebot_bison_target', 'default_schedule_weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nonebot_bison_target', 'default_schedule_weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('nonebot_bison_scheduletimeweight', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
