name: Ruff Lint

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "nonebot_bison/**"
      - "extra_plugins/**"
      - "tests/**"
      - "bot.py"

jobs:
  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Ruff Lint
        uses: chartboost/ruff-action@v1
